//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSR_Client.wwwroot.resources.languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSR_Client.wwwroot.resources.languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        internal static string Dashboard_Appilcations_Action {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applicant response.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_response {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applicant username.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_username {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applications.
        /// </summary>
        internal static string Dashboard_Appilcations_Applications {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applied at.
        /// </summary>
        internal static string Dashboard_Appilcations_Applied_at {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applied at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CoverLetter.
        /// </summary>
        internal static string Dashboard_Appilcations_CoverLetter {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More.
        /// </summary>
        internal static string Dashboard_Appilcations_More {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Dashboard_Appilcations_Name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slug.
        /// </summary>
        internal static string Dashboard_Appilcations_Slug {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status name.
        /// </summary>
        internal static string Dashboard_Appilcations_Status_name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Status name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StatusName.
        /// </summary>
        internal static string Dashboard_Appilcations_StatusName {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacancy title.
        /// </summary>
        internal static string Dashboard_Appilcations_Vacancy_title {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Vacancy title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VacancyResponses.
        /// </summary>
        internal static string Dashboard_Appilcations_VacancyResponses {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:VacancyResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Words.
        /// </summary>
        internal static string Header_Words {
            get {
                return ResourceManager.GetString("Header:Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string Home_About {
            get {
                return ResourceManager.GetString("Home:About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In the modern world of digital technology, voice technologies are becoming increasingly in demand, especially with the development of artificial intelligence and machine learning. However, when it comes to regional languages ​​such as Tajik, special challenges arise. The development of software modules to create a source of voice data in the Tajik language becomes an important step in increasing the availability of technology and introducing innovation in Tajikistan..
        /// </summary>
        internal static string Home_AboutContent {
            get {
                return ResourceManager.GetString("Home:AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tajik Speech Recognition.
        /// </summary>
        internal static string Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home:AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sugd.. ,.
        /// </summary>
        internal static string Home_Address_p1 {
            get {
                return ResourceManager.GetString("Home:Address_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact.
        /// </summary>
        internal static string Home_Contact {
            get {
                return ResourceManager.GetString("Home:Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Us.
        /// </summary>
        internal static string Home_Email {
            get {
                return ResourceManager.GetString("Home:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ubaydulloev.1104@gmail.com.
        /// </summary>
        internal static string Home_EmailLink {
            get {
                return ResourceManager.GetString("Home:EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We are here..
        /// </summary>
        internal static string Home_Hero_Title_1 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   To help you!.
        /// </summary>
        internal static string Home_Hero_Title_2 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The development of software modules for voice data in the Tajik language is aimed at creating systems capable of recognizing and synthesizing speech in the Tajik language. These modules include various components, such as speech recognition algorithms, speech synthesizers, sentiment analyzers and others, capable of working in the Tajik language. The main goal is to make voice interaction technologies accessible to the Tajik language, which will help improve communication, enhance learning and provide access [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Home_MissionContent {
            get {
                return ResourceManager.GetString("Home:MissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The main essence of the direction.
        /// </summary>
        internal static string Home_MissionTitle {
            get {
                return ResourceManager.GetString("Home:MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Us.
        /// </summary>
        internal static string Home_Us {
            get {
                return ResourceManager.GetString("Home:Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internships.
        /// </summary>
        internal static string Internships_Internships {
            get {
                return ResourceManager.GetString("Internships:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jobs.
        /// </summary>
        internal static string Jobs_Jobs {
            get {
                return ResourceManager.GetString("Jobs:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Myself.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New Education.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New Experience.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Skill.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code sent.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company Name.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation code.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmed.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Job.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Of Birth.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Educations.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is not Confirmed!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experience.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experiences.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Name.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you would like to nominate yourself, send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  If you would like to nominate yourself, sign in and send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Current Job.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job Title.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Name.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Profile.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Education.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Experience.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old Password.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal Information.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number is not Confirmed!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Present.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Language.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server is not responding.
        /// </summary>
        internal static string Profile_Serverisnotresponding {
            get {
                return ResourceManager.GetString("Profile:Serverisnotresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skills.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specialty.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Date.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Switch to Dark Theme.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Switch to Light Theme.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Switch to system.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  The status of your CV for your candidacy is.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To change your password, enter your old password, and then create a new, strong password..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try Again.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на University.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Until Now.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload CV.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Upload New CV.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Password.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend code.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send confirmation code.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t have an account? Go to.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forgot your password?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset Password.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue With.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firs name.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your first name.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you have an account? Go to.
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name name.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your last name.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Sign In.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We have sent a confirmation code to this number: $phone$. Please confirm your identity.
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your phone number.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend code.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на seconds left to resend the code..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trainings.
        /// </summary>
        internal static string Trainings_Trainings {
            get {
                return ResourceManager.GetString("Trainings:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applications.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string VacanciesList_All {
            get {
                return ResourceManager.GetString("VacanciesList:All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deadline.
        /// </summary>
        internal static string VacanciesList_Deadline {
            get {
                return ResourceManager.GetString("VacanciesList:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration.
        /// </summary>
        internal static string VacanciesList_Duration {
            get {
                return ResourceManager.GetString("VacanciesList:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End date.
        /// </summary>
        internal static string VacanciesList_End_date {
            get {
                return ResourceManager.GetString("VacanciesList:End date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на month(s).
        /// </summary>
        internal static string VacanciesList_month_s_ {
            get {
                return ResourceManager.GetString("VacanciesList:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are currently no job vacancies available. Please check back later :).
        /// </summary>
        internal static string VacanciesList_NoJobs {
            get {
                return ResourceManager.GetString("VacanciesList:NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posted.
        /// </summary>
        internal static string VacanciesList_Posted {
            get {
                return ResourceManager.GetString("VacanciesList:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string VacanciesList_Search {
            get {
                return ResourceManager.GetString("VacanciesList:Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional Details.
        /// </summary>
        internal static string VacancyApplication_Additional_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Additional Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string VacancyApplication_Apply {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply using profile.
        /// </summary>
        internal static string VacancyApplication_Apply_using_profile {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply using profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply with uploading file.
        /// </summary>
        internal static string VacancyApplication_Apply_with_uploading_file {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply with uploading file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cover Letter.
        /// </summary>
        internal static string VacancyApplication_Cover_Letter {
            get {
                return ResourceManager.GetString("VacancyApplication:Cover Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posted.
        /// </summary>
        internal static string VacancyApplication_Posted {
            get {
                return ResourceManager.GetString("VacancyApplication:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing.
        /// </summary>
        internal static string VacancyApplication_Processing {
            get {
                return ResourceManager.GetString("VacancyApplication:Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Questions.
        /// </summary>
        internal static string VacancyApplication_Questions {
            get {
                return ResourceManager.GetString("VacancyApplication:Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload your CV.
        /// </summary>
        internal static string VacancyApplication_Upload_your_CV {
            get {
                return ResourceManager.GetString("VacancyApplication:Upload your CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Words Details.
        /// </summary>
        internal static string VacancyApplication_Vacancy_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Vacancy Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already have an account?.
        /// </summary>
        internal static string VacancyDetails_Already_have_an_account_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply Now.
        /// </summary>
        internal static string VacancyDetails_Apply_Now {
            get {
                return ResourceManager.GetString("VacancyDetails:Apply Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posted.
        /// </summary>
        internal static string VacancyDetails_Posted {
            get {
                return ResourceManager.GetString("VacancyDetails:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        internal static string VacancyDetails_Sign_In {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string VacancyDetails_Sign_Up {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign Up", resourceCulture);
            }
        }
    }
}
